# Python程序设计与数据处理 · Class 1 作业

**主题：** 导入数据与 DataFrame 基础
**数据：** `datasets/CRSP_Daily_Market_1926_2025.csv` — CRSP 美股市场日度数据（1925 年底 – 2025 年底，共 26,301 个交易日）

> 完成后已同步到 Git 仓库。

## 第 1 题｜导入第三方库

导入 pandas 库（简写为 pd）和 numpy 库（简写为 np），并查看当前 pandas 的版本号。

In [1]:
# 第1题：导入第三方库，并查看 pandas 版本号
import pandas as pd  # 数据处理与分析的核心库，简写为 pd
import numpy as np   # 数值计算库，简写为 np

pd.__version__  # 查看当前 pandas 版本（Notebook 中单独写表达式会直接输出结果）

'3.0.5'

## 第 2 题｜检测文件编码

用 chardet 检测 `datasets/CRSP_Daily_Market_1926_2025.csv` 的编码，并打印检测到的编码名称和置信度。

In [2]:
import chardet

# 直接复用课堂上定义过的 check_encoding() 函数
def check_encoding(filename):
    """检测文件编码，返回 (编码名称, 置信度)"""
    rawdata = open(filename, 'rb').read()   # 以二进制模式读取文件的原始字节
    result = chardet.detect(rawdata)        # chardet 根据字节内容推测编码
    return result['encoding'], result['confidence']

encoding, confidence = check_encoding('datasets/CRSP_Daily_Market_1926_2025.csv')
print(f"Encoding: {encoding}, Confidence: {confidence}")

Encoding: ascii, Confidence: 1.0

## 第 3 题｜读取 CSV 数据

用 `pd.read_csv()` 读取该文件，把结果赋值给变量 `crsp`。文件有两万多行，先读前 5 行确认格式无误，再完整读取。

In [3]:
# ① 先只读前 5 行，快速确认格式无误（大文件先预览是好习惯）
pd.read_csv('datasets/CRSP_Daily_Market_1926_2025.csv', nrows=5)

,DlyCalDt,vwretd,vwretx,vwTotVal,vwUsdVal,vwTotCnt,vwUsdCnt,ewretd,ewretx,ewTotVal,ewUsdVal,ewTotCnt,ewUsdCnt,sprtrn,spindx
0,1925-12-31,NaN,NaN,27487487,NaN,500,NaN,NaN,NaN,27545352,NaN,503,NaN,NaN,NaN
1,1926-01-02,0.005689,0.005689,27600297,27366756.0,494,491.0,0.009516,0.009516,27658600,27424620.0,497,494.0,NaN,NaN
2,1926-01-04,0.000706,0.000706,27577892,27479722.0,499,492.0,0.005780,0.005780,27636515,27538025.0,502,495.0,NaN,NaN
3,1926-01-05,-0.004821,-0.004867,27530213,27561757.0,498,496.0,-0.001927,-0.002030,27588552,27620380.0,501,499.0,NaN,NaN
4,1926-01-06,-0.000423,-0.000427,27618773,27526838.0,502,497.0,0.001182,0.001155,27676674,27585177.0,505,500.0,NaN,NaN

In [4]:
# ② 格式无误，完整读取（两万多行，需要稍等几秒）
crsp = pd.read_csv('datasets/CRSP_Daily_Market_1926_2025.csv')
crsp

,DlyCalDt,vwretd,vwretx,vwTotVal,vwUsdVal,vwTotCnt,vwUsdCnt,ewretd,ewretx,ewTotVal,ewUsdVal,ewTotCnt,ewUsdCnt,sprtrn,spindx
0,1925-12-31,NaN,NaN,27487487,NaN,500,NaN,NaN,NaN,27545352,NaN,503,NaN,NaN,NaN
1,1926-01-02,0.005689,0.005689,27600297,2.736676e+07,494,491.0,0.009516,0.009516,27658600,2.742462e+07,497,494.0,NaN,NaN
2,1926-01-04,0.000706,0.000706,27577892,2.747972e+07,499,492.0,0.005780,0.005780,27636515,2.753802e+07,502,495.0,NaN,NaN
3,1926-01-05,-0.004821,-0.004867,27530213,2.756176e+07,498,496.0,-0.001927,-0.002030,27588552,2.762038e+07,501,499.0,NaN,NaN
4,1926-01-06,-0.000423,-0.000427,27618773,2.752684e+07,502,497.0,0.001182,0.001155,27676674,2.758518e+07,505,500.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26296,2025-12-24,0.002914,0.002904,88568121481,8.831774e+10,9126,9126.0,0.003368,0.003125,90141105180,8.988752e+10,9498,9498.0,0.003221,6932.05
26297,2025-12-26,-0.000242,-0.000325,88542581122,8.856811e+10,9124,9124.0,-0.002105,-0.002373,90125553062,9.014109e+10,9496,9496.0,-0.000304,6929.94
26298,2025-12-29,-0.004191,-0.004230,88169518843,8.854242e+10,9123,9123.0,-0.008373,-0.008603,89739994612,9.012539e+10,9495,9495.0,-0.003492,6905.74
26299,2025-12-30,-0.001550,-0.001576,88028533719,8.816264e+10,9132,9121.0,-0.002831,-0.003547,89596162338,8.973311e+10,9504,9493.0,-0.001376,6896.24
26300,2025-12-31,-0.007319,-0.007491,87552025121,8.802809e+10,9134,9131.0,-0.005245,-0.005627,89118194675,8.959572e+10,9506,9503.0,-0.007358,6845.50

## 第 4 题｜初步认识数据

查看 `crsp` 的行数和列数（shape）、前 5 行（head()）和后 5 行（tail()），并打印出所有的列名。

In [5]:
crsp.shape  # (行数, 列数)：注意 shape 是属性，后面不加括号

(26301, 15)

In [6]:
crsp.head()  # 查看前 5 行

,DlyCalDt,vwretd,vwretx,vwTotVal,vwUsdVal,vwTotCnt,vwUsdCnt,ewretd,ewretx,ewTotVal,ewUsdVal,ewTotCnt,ewUsdCnt,sprtrn,spindx
0,1925-12-31,NaN,NaN,27487487,NaN,500,NaN,NaN,NaN,27545352,NaN,503,NaN,NaN,NaN
1,1926-01-02,0.005689,0.005689,27600297,27366756.0,494,491.0,0.009516,0.009516,27658600,27424620.0,497,494.0,NaN,NaN
2,1926-01-04,0.000706,0.000706,27577892,27479722.0,499,492.0,0.005780,0.005780,27636515,27538025.0,502,495.0,NaN,NaN
3,1926-01-05,-0.004821,-0.004867,27530213,27561757.0,498,496.0,-0.001927,-0.002030,27588552,27620380.0,501,499.0,NaN,NaN
4,1926-01-06,-0.000423,-0.000427,27618773,27526838.0,502,497.0,0.001182,0.001155,27676674,27585177.0,505,500.0,NaN,NaN

In [7]:
crsp.tail()  # 查看后 5 行：数据已更新到 2025 年末

,DlyCalDt,vwretd,vwretx,vwTotVal,vwUsdVal,vwTotCnt,vwUsdCnt,ewretd,ewretx,ewTotVal,ewUsdVal,ewTotCnt,ewUsdCnt,sprtrn,spindx
26296,2025-12-24,0.002914,0.002904,88568121481,8.831774e+10,9126,9126.0,0.003368,0.003125,90141105180,8.988752e+10,9498,9498.0,0.003221,6932.05
26297,2025-12-26,-0.000242,-0.000325,88542581122,8.856811e+10,9124,9124.0,-0.002105,-0.002373,90125553062,9.014109e+10,9496,9496.0,-0.000304,6929.94
26298,2025-12-29,-0.004191,-0.004230,88169518843,8.854242e+10,9123,9123.0,-0.008373,-0.008603,89739994612,9.012539e+10,9495,9495.0,-0.003492,6905.74
26299,2025-12-30,-0.001550,-0.001576,88028533719,8.816264e+10,9132,9121.0,-0.002831,-0.003547,89596162338,8.973311e+10,9504,9493.0,-0.001376,6896.24
26300,2025-12-31,-0.007319,-0.007491,87552025121,8.802809e+10,9134,9131.0,-0.005245,-0.005627,89118194675,8.959572e+10,9506,9503.0,-0.007358,6845.50

In [8]:
print(crsp.columns)  # 打印所有列名

Index(['DlyCalDt', 'vwretd', 'vwretx', 'vwTotVal', 'vwUsdVal', 'vwTotCnt',
       'vwUsdCnt', 'ewretd', 'ewretx', 'ewTotVal', 'ewUsdVal', 'ewTotCnt',
       'ewUsdCnt', 'sprtrn', 'spindx'],
      dtype='str')

## 第 5 题｜数据的基本信息与统计摘要

用 `info()` 和 `describe()` 查看 `crsp` 的列类型和统计摘要。
**思考：** vwretd、sprtrn 这些列名可能是什么意思？为什么 sprtrn、spindx 的非缺失值个数明显更少？

In [9]:
crsp.info()  # 每一列的列名、非缺失值个数、数据类型

<class 'pandas.DataFrame'>
RangeIndex: 26301 entries, 0 to 26300
Data columns (total 15 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   DlyCalDt  26301 non-null  str
 1   vwretd    26300 non-null  float64
 2   vwretx    26300 non-null  float64
 3   vwTotVal  26301 non-null  int64
 4   vwUsdVal  26300 non-null  float64
 5   vwTotCnt  26301 non-null  int64
 6   vwUsdCnt  26300 non-null  float64
 7   ewretd    26300 non-null  float64
 8   ewretx    26300 non-null  float64
 9   ewTotVal  26301 non-null  int64
 10  ewUsdVal  26300 non-null  float64
 11  ewTotCnt  26301 non-null  int64
 12  ewUsdCnt  26300 non-null  float64
 13  sprtrn    15981 non-null  float64
 14  spindx    15982 non-null  float64
dtypes: float64(10), int64(4), str(1)
memory usage: 3.3 MB

In [10]:
crsp.describe()  # 数值列的统计摘要：个数、均值、标准差、最大/最小值等

,vwretd,vwretx,vwTotVal,vwUsdVal,vwTotCnt,vwUsdCnt,ewretd,ewretx,ewTotVal,ewUsdVal,ewTotCnt,ewUsdCnt,sprtrn,spindx
count,26300.000000,26300.000000,2.630100e+04,2.630000e+04,26301.000000,26300.000000,26300.000000,26300.000000,2.630100e+04,2.630000e+04,26301.000000,26300.000000,15981.000000,15982.000000
mean,0.000421,0.000286,8.463483e+09,8.459652e+09,3935.620661,3930.434487,0.000801,0.000689,8.699635e+09,8.695712e+09,4075.014980,4071.904411,0.000355,1088.306449
std,0.010710,0.010709,1.555537e+10,1.554715e+10,2899.110650,2896.441375,0.010570,0.010572,1.593272e+10,1.592440e+10,3042.168464,3041.323725,0.010357,1371.250067
min,-0.171345,-0.171419,1.229773e+07,1.228914e+07,406.000000,404.000000,-0.135468,-0.135510,1.243940e+07,1.243080e+07,408.000000,406.000000,-0.204669,53.490000
25%,-0.003854,-0.003980,6.339168e+07,6.330839e+07,944.000000,943.000000,-0.003011,-0.003138,6.372042e+07,6.365784e+07,947.000000,946.000000,-0.004274,106.325000
50%,0.000759,0.000624,7.730611e+08,7.728701e+08,4753.000000,4747.000000,0.001280,0.001172,7.956396e+08,7.954800e+08,4827.000000,4821.000000,0.000485,460.845000
75%,0.005075,0.004952,1.204819e+10,1.204109e+10,6630.000000,6608.000000,0.005063,0.004956,1.237183e+10,1.237003e+10,6876.000000,6872.000000,0.005240,1376.532500
max,0.156838,0.152974,8.856812e+10,8.856811e+10,9166.000000,9163.000000,0.203020,0.201795,9.014111e+10,9.014109e+10,9538.000000,9535.000000,0.115800,6932.050000

**思考题回答：**

- `vwretd` / `vwretx`：市值加权（value-weighted）市场日收益率，含 / 不含股息；`ewretd` / `ewretx`：等权重（equal-weighted）日收益率；`sprtrn`：标普 500 日收益率；`spindx`：标普 500 指数点位。
- `sprtrn`、`spindx` 的非缺失值只有约 1.6 万条（15,981 / 15,982），明显少于全表的 26,301 条：因为标普 500 的相关数据**从 1962 年 7 月才开始有**（首条有效数据为 1962-07-03），之前年份为缺失值。

## 第 6 题｜选择列

① 用单层中括号取出 `sprtrn` 这一列（结果是 Series），并用 `type()` 验证它的类型；
② 用双层中括号同时取出 `DlyCalDt` 和 `sprtrn` 两列（结果是 DataFrame），同样用 `type()` 验证。

In [11]:
# ① 单层中括号：取出一列，结果是 Series（序列）
type(crsp['sprtrn'])

pandas.Series

In [12]:
# ② 双层中括号 + 列名列表：取出多列，结果仍是 DataFrame（数据框）
type(crsp[['DlyCalDt', 'sprtrn']])

pandas.DataFrame

## 第 7 题｜选择行

① 用 `iloc` 选出第 0 行到第 4 行、第 0 列到第 2 列的数据；
② 用 `at` 取出第 1 行 `vwretd` 列的数值（第 0 行是 1925-12-31，当日还没有收益率，为缺失值）；
③ 用 `loc` 选出第 0 行到第 4 行、且只包含 `DlyCalDt` 和 `vwretd` 两列的数据。注意 iloc 和 loc 切片的区别。

In [13]:
# ① iloc 按位置（行号、列号）选取：第 0~4 行、第 0~2 列
crsp.iloc[0:5, 0:3]

     DlyCalDt    vwretd    vwretx
0  1925-12-31       NaN       NaN
1  1926-01-02  0.005689  0.005689
2  1926-01-04  0.000706  0.000706
3  1926-01-05 -0.004821 -0.004867
4  1926-01-06 -0.000423 -0.000427

In [14]:
# ② at 按"行索引 + 列名"取单个元素：第 1 行 vwretd 列
crsp.at[1, 'vwretd']

np.float64(0.005689)

In [15]:
# ③ loc 按标签切片：第 0~4 行、只取 DlyCalDt 和 vwretd 两列
# 注意：loc 的切片【包含】右端点（0:4 取到第 4 行），与 iloc 相反
crsp.loc[0:4, ['DlyCalDt', 'vwretd']]

     DlyCalDt    vwretd
0  1925-12-31       NaN
1  1926-01-02  0.005689
2  1926-01-04  0.000706
3  1926-01-05 -0.004821
4  1926-01-06 -0.000423

## 第 8 题｜日期处理三步曲

① 把 `DlyCalDt` 列从文本转换为 datetime 格式（格式为 %Y-%m-%d）；
② 按 `DlyCalDt` 列升序排序；
③ 把 `DlyCalDt` 列设为索引。每一步都运行显示一下 `crsp`，确认结果正确。

In [16]:
# 第①步：文本 → datetime（日期格式为 %Y-%m-%d，如 1925-12-31）
crsp['DlyCalDt'] = pd.to_datetime(crsp['DlyCalDt'], format='%Y-%m-%d')
crsp.head(3)  # 确认日期列已变成真正的日期格式

,DlyCalDt,vwretd,vwretx,vwTotVal,vwUsdVal,vwTotCnt,vwUsdCnt,ewretd,ewretx,ewTotVal,ewUsdVal,ewTotCnt,ewUsdCnt,sprtrn,spindx
0,1925-12-31,NaN,NaN,27487487,NaN,500,NaN,NaN,NaN,27545352,NaN,503,NaN,NaN,NaN
1,1926-01-02,0.005689,0.005689,27600297,27366756.0,494,491.0,0.009516,0.009516,27658600,27424620.0,497,494.0,NaN,NaN
2,1926-01-04,0.000706,0.000706,27577892,27479722.0,499,492.0,0.005780,0.005780,27636515,27538025.0,502,495.0,NaN,NaN

In [17]:
# 第②步：按 DlyCalDt 升序排序（从旧到新）
crsp = crsp.sort_values(by='DlyCalDt', ascending=True)
crsp.head(3)  # 确认：最早的数据排在最上面

,DlyCalDt,vwretd,vwretx,vwTotVal,vwUsdVal,vwTotCnt,vwUsdCnt,ewretd,ewretx,ewTotVal,ewUsdVal,ewTotCnt,ewUsdCnt,sprtrn,spindx
0,1925-12-31,NaN,NaN,27487487,NaN,500,NaN,NaN,NaN,27545352,NaN,503,NaN,NaN,NaN
1,1926-01-02,0.005689,0.005689,27600297,27366756.0,494,491.0,0.009516,0.009516,27658600,27424620.0,497,494.0,NaN,NaN
2,1926-01-04,0.000706,0.000706,27577892,27479722.0,499,492.0,0.005780,0.005780,27636515,27538025.0,502,495.0,NaN,NaN

In [18]:
# 第③步：把 DlyCalDt 设为索引——之后就可以按时间直接筛选
crsp.set_index('DlyCalDt', inplace=True)
crsp

,vwretd,vwretx,vwTotVal,vwUsdVal,vwTotCnt,vwUsdCnt,ewretd,ewretx,ewTotVal,ewUsdVal,ewTotCnt,ewUsdCnt,sprtrn,spindx
DlyCalDt,,,,,,,,,,,,,,
1925-12-31,NaN,NaN,27487487,NaN,500,NaN,NaN,NaN,27545352,NaN,503,NaN,NaN,NaN
1926-01-02,0.005689,0.005689,27600297,2.736676e+07,494,491.0,0.009516,0.009516,27658600,2.742462e+07,497,494.0,NaN,NaN
1926-01-04,0.000706,0.000706,27577892,2.747972e+07,499,492.0,0.005780,0.005780,27636515,2.753802e+07,502,495.0,NaN,NaN
1926-01-05,-0.004821,-0.004867,27530213,2.756176e+07,498,496.0,-0.001927,-0.002030,27588552,2.762038e+07,501,499.0,NaN,NaN
1926-01-06,-0.000423,-0.000427,27618773,2.752684e+07,502,497.0,0.001182,0.001155,27676674,2.758518e+07,505,500.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-12-24,0.002914,0.002904,88568121481,8.831774e+10,9126,9126.0,0.003368,0.003125,90141105180,8.988752e+10,9498,9498.0,0.003221,6932.05
2025-12-26,-0.000242,-0.000325,88542581122,8.856811e+10,9124,9124.0,-0.002105,-0.002373,90125553062,9.014109e+10,9496,9496.0,-0.000304,6929.94
2025-12-29,-0.004191,-0.004230,88169518843,8.854242e+10,9123,9123.0,-0.008373,-0.008603,89739994612,9.012539e+10,9495,9495.0,-0.003492,6905.74
2025-12-30,-0.001550,-0.001576,88028533719,8.816264e+10,9132,9121.0,-0.002831,-0.003547,89596162338,8.973311e+10,9504,9493.0,-0.001376,6896.24
2025-12-31,-0.007319,-0.007491,87552025121,8.802809e+10,9134,9131.0,-0.005245,-0.005627,89118194675,8.959572e+10,9506,9503.0,-0.007358,6845.50

## 第 9 题｜按时间筛选

用上题的 `crsp`，筛选出 2020 年全年的数据（2020 年爆发了新冠疫情，美股出现剧烈波动），把结果赋值给变量 `crsp_2020`。检查筛选结果的行数大约是多少个交易日？

In [19]:
# DlyCalDt 已是索引，直接用年份 '2020' 切片筛选全年
crsp_2020 = crsp.loc['2020']
print('2020年交易日数：', crsp_2020.shape[0])
crsp_2020.head()  # 查看筛选结果的前几行

2020年交易日数： 253

,vwretd,vwretx,vwTotVal,vwUsdVal,vwTotCnt,vwUsdCnt,ewretd,ewretx,ewTotVal,ewUsdVal,ewTotCnt,ewUsdCnt,sprtrn,spindx
DlyCalDt,,,,,,,,,,,,,,
2020-01-02,0.007412,0.007316,41464754137,4.115634e+10,6871,6866.0,0.005470,0.005428,42902996443,4.255570e+10,7253,7248.0,0.008379,3257.85
2020-01-03,-0.005828,-0.005900,41221078749,4.146475e+10,6871,6871.0,-0.003057,-0.003072,42645264616,4.290300e+10,7253,7253.0,-0.007060,3234.85
2020-01-06,0.003269,0.003245,41345986288,4.121183e+10,6871,6869.0,0.004548,0.004519,42768514163,4.263602e+10,7253,7251.0,0.003533,3246.28
2020-01-07,-0.002147,-0.002216,41255461753,4.134598e+10,6870,6870.0,-0.000041,-0.000057,42699866212,4.276851e+10,7253,7252.0,-0.002803,3237.18
2020-01-08,0.004028,0.003996,41421675525,4.125546e+10,6871,6870.0,0.000914,0.000903,42870237688,4.269987e+10,7254,7253.0,0.004902,3253.05

**检查结果：** 2020 年共筛选出 **253 个交易日**（2020-01-02 至 2020-12-31），与美股 2020 年实际交易日数量一致。

## 第 10 题｜保存数据

把筛选出的 `crsp_2020` 保存为 `datasets/CRSP_2020.csv`，要求：
① 把日期索引一并写入文件；② 用 Excel 直接打开时不出现乱码。保存后用 `pd.read_csv()` 重新读回来，验证文件是否正确生成。

In [20]:
# 保存：index=True 把日期索引一并写入；encoding='utf-8-sig' 保证用 Excel 打开中文不乱码
crsp_2020.to_csv('datasets/CRSP_2020.csv', index=True, encoding='utf-8-sig')

In [21]:
# 读回验证：文件能正常读回来，说明保存成功
pd.read_csv('datasets/CRSP_2020.csv').head()

,DlyCalDt,vwretd,vwretx,vwTotVal,vwUsdVal,vwTotCnt,vwUsdCnt,ewretd,ewretx,ewTotVal,ewUsdVal,ewTotCnt,ewUsdCnt,sprtrn,spindx
0,2020-01-02,0.007412,0.007316,41464754137,4.115634e+10,6871,6866.0,0.005470,0.005428,42902996443,4.255570e+10,7253,7248.0,0.008379,3257.85
1,2020-01-03,-0.005828,-0.005900,41221078749,4.146475e+10,6871,6871.0,-0.003057,-0.003072,42645264616,4.290300e+10,7253,7253.0,-0.007060,3234.85
2,2020-01-06,0.003269,0.003245,41345986288,4.121183e+10,6871,6869.0,0.004548,0.004519,42768514163,4.263602e+10,7253,7251.0,0.003533,3246.28
3,2020-01-07,-0.002147,-0.002216,41255461753,4.134598e+10,6870,6870.0,-0.000041,-0.000057,42699866212,4.276851e+10,7253,7252.0,-0.002803,3237.18
4,2020-01-08,0.004028,0.003996,41421675525,4.125546e+10,6871,6870.0,0.000914,0.000903,42870237688,4.269987e+10,7254,7253.0,0.004902,3253.05

## （选做）拓展题｜读取 Excel 文件

运行 `help(pd.read_excel)`，自学 Excel 文件的读取方法。

In [22]:
# 查看 read_excel 的帮助文档（帮助内容较长，可重点看 io、sheet_name、header 等参数，与 read_csv 类似）
help(pd.read_excel)

# 注：本仓库暂无 .xlsx 数据文件，掌握方法后按如下方式即可读取：
# pd.read_excel('文件名.xlsx', sheet_name='Sheet1')

Help on function read_excel in module pandas:

read_excel(
    io,
    sheet_name: 'str | int | list[IntStrT] | None' = 0,
    *,
    header: 'int | Sequence[int] | None' = 0,
    names: 'SequenceNotStr[Hashable] | range | None' = None,
    index_col: 'int | str | Sequence[int] | None' = None,
    usecols: 'int | str | Sequence[int] | Sequence[str] | Callable[[HashableT], bool] | None' = None,
    dtype: 'DtypeArg | None' = None,
    engine: "Literal['xlrd', 'openpyxl', 'odf', 'pyxlsb', 'calamine'] | None" = None,
    converters: 'dict[str, Callable] | dict[int, Callable] | None' = None,
    true_values: 'Iterable[Hashable] | None' = None,
    false_values: 'Iterable[Hashable] | None' = None,
    skiprows: 'Sequence[int] | int | Callable[[int], object] | None' = None,
    nrows: 'int | None' = None,
    na_values=None,
    keep_default_na: 'bool' = True,
    na_filter: 'bool' = True,
    verbose: 'bool' = False,
    parse_dates: 'list | dict | bool' = False,
    date_format: 'dict[Hashable, str] | str | None' = None,
    thousands: 'str | None' = None,
    decimal: 'str' = '.',
    comment: 'str | None' = None,
    skipfooter: 'int' = 0,
    storage_options: 'StorageOptions | None' = None,
    dtype_backend: 'DtypeBackend | lib.NoDefault' = <no_default>,
    engine_kwargs: 'dict | None' = None
) -> 'DataFrame | dict[IntStrT, DataFrame]'
    Read an Excel file into a ``DataFrame``.

    Supports `xls`, `xlsx`, `xlsm`, `xlsb`, `odf`, `ods` and `odt` file extensions
    read from a local filesystem or URL. Supports an option to read
    a single sheet or a list of sheets.

    Parameters
    ----------
    io : str, ExcelFile, xlrd.Book, path object, or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, and file. For file URLs, a host is
        expected. A local file could be: ``file://localhost/path/to/table.xlsx``.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method,
        such as a file handle (e.g. via builtin ``open`` function)
        or ``StringIO``.

    sheet_name : str, int, list, or None, default 0
        Strings are used for sheet names. Integers are used in zero-indexed
        sheet positions (chart sheets do not count as a sheet position).
        Lists of strings/integers are used to request multiple sheets.
        When ``None``, will return a dictionary containing DataFrames for each sheet.

        Available cases:

        * Defaults to ``0``: 1st sheet as a `DataFrame`
        * ``1``: 2nd sheet as a `DataFrame`
        * ``"Sheet1"``: Load sheet with name "Sheet1"
        * ``[0, 1, "Sheet5"]``: Load first, second and sheet named "Sheet5"
          as a dict of `DataFrame`
        * ``None``: Returns a dictionary containing DataFrames for each sheet.

    header : int, list of int, default 0
        Row (0-indexed) to use for the column labels of the parsed
        DataFrame. If a list of integers is passed those row positions will
        be combined into a ``MultiIndex``. Use None if there is no header.
    names : array-like, default None
        List of column names to use. If file contains no header row,
        then you should explicitly pass header=None.
    index_col : int, str, list of int, default None
        Column (0-indexed) to use as the row labels of the DataFrame.
        Pass None if there is no such column.  If a list is passed,
        those columns will be combined into a ``MultiIndex``.  If a
        subset of data is selected with ``usecols``, index_col
        is based on the subset.

        Missing values will be forward filled to allow roundtripping with
        ``to_excel`` for ``merged_cells=True``. To avoid forward filling the
        missing values use ``set_index`` after reading the data instead of
        ``index_col``.
    usecols : str, list-like, or callable, default None
        * If None, then parse all columns.
        * If str, then indicates comma separated list of Excel column letters
          and column ranges (e.g. "A:E" or "A,C,E:F"). Ranges are inclusive of
          both sides.
        * If list of int, then indicates list of column numbers to be parsed
          (0-indexed).
        * If list of string, then indicates list of column names to be parsed.
        * If callable, then evaluate each column name against it and parse the
          column if the callable returns ``True``.

        Returns a subset of the columns according to behavior above.
    dtype : Type name or dict of column -> type, default None
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
        Use ``object`` to preserve data as stored in Excel and not interpret dtype,
        which will necessarily result in ``object`` dtype.
        If converters are specified, they will be applied INSTEAD
        of dtype conversion.
        If you use ``None``, it will infer the dtype of each column based on the data.
    engine : {'openpyxl', 'calamine', 'odf', 'pyxlsb', 'xlrd'}, default None
        If io is not a buffer or path, this must be set to identify io.
        Engine compatibility :

        - ``openpyxl`` supports newer Excel file formats.
        - ``calamine`` supports Excel (.xls, .xlsx, .xlsm, .xlsb)
          and OpenDocument (.ods) file formats.
        - ``odf`` supports OpenDocument file formats (.odf, .ods, .odt).
        - ``pyxlsb`` supports Binary Excel files.
        - ``xlrd`` supports old-style Excel files (.xls).

        When ``engine=None``, the following logic will be used to determine the engine:

        - If ``path_or_buffer`` is an OpenDocument format (.odf, .ods, .odt),
          then `odf <https://pypi.org/project/odfpy/>`_ will be used.
        - Otherwise if ``path_or_buffer`` is an xls format, ``xlrd`` will be used.
        - Otherwise if ``path_or_buffer`` is in xlsb format, ``pyxlsb`` will be used.
        - Otherwise ``openpyxl`` will be used.

    converters : dict, default None
        Dict of functions for converting values in certain columns. Keys can
        either be integers or column labels, values are functions that take one
        input argument, the Excel cell content, and return the transformed
        content.
    true_values : list, default None
        Values to consider as True.
    false_values : list, default None
        Values to consider as False.
    skiprows : list-like, int, or callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (int) at the
        start of the file. If callable, the callable function will be evaluated
        against the row indices, returning True if the row should be skipped and
        False otherwise. An example of a valid callable argument would be ``lambda
        x: x in [0, 2]``.
    nrows : int, default None
        Number of rows to parse. Does not include header rows.
    na_values : scalar, str, list-like, or dict, default None
        Additional strings to recognize as NA/NaN. If dict passed, specific
        per-column NA values. By default the following values are interpreted
        as NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
        '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'None',
        'n/a', 'nan', 'null'.
    keep_default_na : bool, default True
        Whether or not to include the default NaN values when parsing the data.
        Depending on whether ``na_values`` is passed in, the behavior is as follows:

        * If ``keep_default_na`` is True, and ``na_values`` are specified,
          ``na_values`` is appended to the default NaN values used for parsing.
        * If ``keep_default_na`` is True, and ``na_values`` are not specified, only
          the default NaN values are used for parsing.
        * If ``keep_default_na`` is False, and ``na_values`` are specified, only
          the NaN values specified ``na_values`` are used for parsing.
        * If ``keep_default_na`` is False, and ``na_values`` are not specified, no
          strings will be parsed as NaN.

        Note that if `na_filter` is passed in as False, the ``keep_default_na`` and
        ``na_values`` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of na_values). In
        data without any NAs, passing ``na_filter=False`` can improve the
        performance of reading a large file.
    verbose : bool, default False
        Indicate number of NA values placed in non-numeric columns.
    parse_dates : bool, list-like, or dict, default False
        The behavior is as follows:

        * ``bool``. If True -> try parsing the index.
        * ``list`` of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
          each as a separate date column.
        * ``list`` of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
          a single date column.
        * ``dict``, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
          result 'foo'

        If a column or index contains an unparsable date, the entire column or
        index will be returned unaltered as an object data type. If you don`t want to
        parse some cells as date just change their type in Excel to "Text".
        For non-standard datetime parsing, use ``pd.to_datetime`` after
        ``pd.read_excel``.

        Note: A fast-path exists for iso8601-formatted dates.
    date_format : str or dict of column -> format, default ``None``
        If used in conjunction with ``parse_dates``, will parse dates according to this
        format. For anything more complex,
        please read in as ``object`` and then apply :func:`to_datetime` as-needed.

        .. versionadded:: 2.0.0

    thousands : str, default None
        Thousands separator for parsing string columns to numeric.  Note that
        this parameter is only necessary for columns stored as TEXT in Excel,
        any numeric columns will automatically be parsed, regardless of display
        format.
    decimal : str, default '.'
        Character to recognize as decimal point for parsing string columns to numeric.
        Note that this parameter is only necessary for columns stored as TEXT in Excel,
        any numeric columns will automatically be parsed, regardless of display
        format.(e.g. use ',' for European data).
    comment : str, default None
        Comments out remainder of line. Pass a character or characters to this
        argument to indicate comments in the input file. Any data between the
        comment string and the end of the current line is ignored.
    skipfooter : int, default 0
        Rows at the end to skip (0-indexed).
    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
        are forwarded to ``urllib.request.Request`` as header options. For other
        URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
        forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
        details, and for more examples on storage options refer `here
        <https://pandas.pydata.org/docs/user_guide/io.html?
        highlight=storage_options#reading-writing-remote-files>`_.

    dtype_backend : {'numpy_nullable', 'pyarrow'}
        Back-end data type applied to the resultant :class:`DataFrame`
        (still experimental). If not specified, the default behavior
        is to not use nullable data types. If specified, the behavior
        is as follows:

        * ``"numpy_nullable"``: returns nullable-dtype-backed :class:`DataFrame`
        * ``"pyarrow"``: returns pyarrow-backed nullable

        :class:`ArrowDtype` :class:`DataFrame`

        .. versionadded:: 2.0

    engine_kwargs : dict, optional
        Arbitrary keyword arguments passed to excel engine.

    Returns
    -------
    DataFrame or dict of DataFrames
        DataFrame from the passed in Excel file. See notes in sheet_name
        argument for more information on when a dict of DataFrames is returned.

    See Also
    --------
    DataFrame.to_excel : Write DataFrame to an Excel file.
    DataFrame.to_csv : Write DataFrame to a comma-separated values (csv) file.
    read_csv : Read a comma-separated values (csv) file into DataFrame.
    read_fwf : Read a table of fixed-width formatted lines into DataFrame.

    Notes
    -----
    For specific information on the methods used for each Excel engine, refer to the
    pandas
    :ref:`user guide <io.excel_reader>`

    Examples
    --------
    The file can be read using the file name as string or an open file object:

    >>> pd.read_excel("tmp.xlsx", index_col=0)  # doctest: +SKIP
           Name  Value
    0   string1      1
    1   string2      2
    2  #Comment      3

    >>> pd.read_excel(open("tmp.xlsx", "rb"), sheet_name="Sheet3")  # doctest: +SKIP
       Unnamed: 0      Name  Value
    0           0   string1      1
    1           1   string2      2
    2           2  #Comment      3

    Index and header can be specified via the `index_col` and `header` arguments

    >>> pd.read_excel("tmp.xlsx", index_col=None, header=None)  # doctest: +SKIP
         0         1      2
    0  NaN      Name  Value
    1  0.0   string1      1
    2  1.0   string2      2
    3  2.0  #Comment      3

    Column types are inferred but can be explicitly specified

    >>> pd.read_excel(
    ...     "tmp.xlsx", index_col=0, dtype={"Name": str, "Value": float}
    ... )  # doctest: +SKIP
           Name  Value
    0   string1    1.0
    1   string2    2.0
    2  #Comment    3.0

    True, False, and NA values, and thousands separators have defaults,
    but can be explicitly specified, too. Supply the values you would like
    as strings or lists of strings!

    >>> pd.read_excel(
    ...     "tmp.xlsx", index_col=0, na_values=["string1", "string2"]
    ... )  # doctest: +SKIP
           Name  Value
    0       NaN      1
    1       NaN      2
    2  #Comment      3

    Comment lines in the excel input file can be skipped using the
    ``comment`` kwarg.

    >>> pd.read_excel("tmp.xlsx", index_col=0, comment="#")  # doctest: +SKIP
          Name  Value
    0  string1    1.0
    1  string2    2.0
    2     None    NaN